# -*- mode: ruby -*-
# vi: set ft=ruby :
# vagrant plugin install vagrant-vbguest
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "get_live"
  config.vm.network :private_network, ip: "192.168.34.20"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/3657281/centos64_ja.box"
  # config.vm.box_url = "../../../centos64_ja.box"
  config.vm.synced_folder "../", "/var/www/html/current", create: true, owner: "vagrant", group: "vagrant", mount_options:['dmode=777','fmode=777']
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true

  config.vm.provider :virtualbox do |vb|
    vb.name = "get_live"
    vb.gui = false
    # vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision "shell", privileged: false do |shell|
    shell.path = "setup.sh"
    shell.args = 'vagrant'
  end
end
